jobs:
- name: pull-request
  plan:
    - in_parallel:
      - get: pull-request
        version: every
        trigger: true

      - get: base-image
        trigger: true
        params:
          format: oci

      - get: common-pipelines
        trigger: true

    - put: pull-request
      params:
        path: pull-request
        status: pending

    - task: oci-build
      privileged: true
      file: common-pipelines/container/oci-build.yml
      input_mapping:
        src: pull-request
      params: ((oci-build-params)) # for available params, see https://github.com/concourse/oci-build-task#params

    - in_parallel:
      - task: usg-audit
        privileged: true
        file: common-pipelines/container/usg-audit.yml
        image: image

      - do:
        - task: scan-image
          file: common-pipelines/container/scan-image.yml

        - task: cve-check
          file: common-pipelines/container/cve-check.yml

  on_failure:
    put: pull-request
    params:
      path: pull-request
      status: failure

- name: main
  plan:
    - in_parallel:
      - get: src
        trigger: true

      - get: base-image
        trigger: true
        params:
          format: oci

      - get: common-pipelines
        trigger: true

    - task: oci-build
      privileged: true
      file: common-pipelines/container/oci-build.yml
      params: ((oci-build-params)) # for available params, see https://github.com/concourse/oci-build-task#params

    - in_parallel:
      - task: usg-audit
        file: common-pipelines/container/usg-audit.yml
        image: image

      - do:
        - task: scan-image
          file: common-pipelines/container/scan-image.yml

        - task: cve-check
          file: common-pipelines/container/cve-check.yml

    - put: image
      inputs:
        - image
        - src
      params:
        image: image/image.tar
        additional_tags: src/.git/short_ref

  on_failure:
    put: slack
    params:
      text:  |
        :x: Pipeline `$BUILD_PIPELINE_NAME` FAILED to upload image to ECR
        <$ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|View build details>
      channel: '#cg-platform-news'
      username: ((slack-username))
      icon_url: https://avatars1.githubusercontent.com/u/7809479?v=3&s=40


resources:

- name: base-image
  type: registry-image
  source:
    aws_access_key_id: ((ecr_aws_key))
    aws_secret_access_key: ((ecr_aws_secret))
    repository: ((base-image))
    tag: ((base-image-tag))
    aws_region: us-gov-west-1

- name: common-pipelines
  type: git
  source:
    uri: https://github.com/cloud-gov/common-pipelines
    branch: main
    commit_verification_keys: ((cloud-gov-pgp-keys))

- name: image
  type: registry-image
  source:
    aws_access_key_id: ((ecr_aws_key))
    aws_secret_access_key: ((ecr_aws_secret))
    repository: ((image-repository))
    tag: latest
    aws_region: us-gov-west-1

- name: pull-request
  type: pull-request
  check_every: 1m
  source:
    repository: ((src-repo))
    access_token: ((cg-ci-bot-ghtoken))
    disable_forks: true
    base_branch: main

- name: slack
  type: slack-notification
  source:
    url: ((slack-webhook-url))

- name: src
  type: git
  source:
    uri: https://github.com/((src-repo))
    branch: main
    commit_verification_keys: ((cloud-gov-pgp-keys))

resource_types:
- name: slack-notification
  type: registry-image
  source:
    repository: cfcommunity/slack-notification-resource

- name: pull-request
  type: registry-image
  source:
    repository: teliaoss/github-pr-resource
