jobs:
- name: set-self
  plan:
    - get: common-pipelines
      trigger: true
    - get: src
      trigger: false
    - set_pipeline: self
      file: common-pipelines/container/pipeline.yml
      var_files:
        - src/container/ci/vars.yml

- name: pull-request
  plan:
    - get: pull-request
      version: every
      trigger: true

    - get: common-pipelines
      passed: [set-self]
      trigger: true

    - put: pull-request
      params:
        path: pull-request
        status: pending

    - task: oci-build
      privileged: true
      file: common-pipelines/container/oci-build.yml
      input_mapping:
        src: pull-request
      params: ((oci-build-params)) # for available params, see https://github.com/concourse/oci-build-task#params

    - in_parallel:
      - task: usg-audit
        file: common-pipelines/container/usg-audit.yml
        image: image

      - task: scan-image
        file: common-pipelines/container/scan-image.yml

  on_failure:
    put: pull-request
    params:
      path: pull-request
      status: failure


resources:

- name: common-pipelines
  type: git
  source:
    uri: https://github.com/cloud-gov/common-pipelines
    branch: main
    commit_verification_keys: ((cloud-gov-pgp-keys))

- name: src
  type: git
  source:
    uri: https://github.com/((src-repo))
    branch: main
    commit_verification_keys: ((cloud-gov-pgp-keys))

- name: pull-request
  type: pull-request
  check_every: 1m
  source:
    repository: ((src-repo))
    access_token: ((cg-ci-bot-ghtoken))
    disable_forks: true
    base_branch: main

resource_types:
- name: slack-notification
  type: registry-image
  source:
    repository: cfcommunity/slack-notification-resource

- name: pull-request
  type: registry-image
  source:
    repository: teliaoss/github-pr-resource
