jobs:
- name: set-self
  plan:
    - get: common-pipelines
      trigger: true
    - set_pipeline: self
      file: common-pipelines/go/pipeline.yml

# todo: passed: [set-self], trigger: true?
- name: pull-request
  plan:
  - get: pull-request
    version: every
    trigger: true
  - get: common-pipelines
    passed: [set-self]
  - put: pull-request
    params:
      path: pull-request
      status: pending
  - task: go-build
    file: common-pipelines/go/go-build.yml
    input_mapping:
      src: pull-request
  on_failure:
    put: pull-request
    params:
      path: pull-request
      status: failure

resources:
- name: pull-request
  type: pull-request
  check_every: 1m
  source:
    repository: ((src-repo))
    access_token: ((cg-ci-bot-ghtoken))
    disable_forks: true
    base_branch: testing

- name: common-pipelines
  type: git
  source:
    uri: https://github.com/cloud-gov/common-pipelines
    branch: testing
    commit_verification_keys: ((cloud-gov-pgp-keys))

resource_types:
- name: slack-notification
  type: docker-image
  source:
    repository: cfcommunity/slack-notification-resource

- name: pull-request
  type: docker-image
  source:
    repository: teliaoss/github-pr-resource
